# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-us'

# Website info
name: 'Anthony DeSouza'
description: "A personal blog with a focus of data science, machine learning, and other software experiments"

# Author's info
author: 'Anthony DeSouza'
# edit 'categories' in the front matter of every post to match this username
bio: 'Studying software engineering, I have an interest in machine learning, data science, and the application of technology to improve life.'
location: 'Ontario, Canada'
url: 'https://desouza.li'
# image: 'assets/images/casper.png'

short_url: 'desouza.li'
google_analytics: UA-100869751-2
disqus: desouza
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

jscdn:
  - math: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - fabric: //cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.13/fabric.js
  - chart: https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js
  - svg: https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.2/svg.min.js
# - fabric: //cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.13/fabric.min.js


# gems and other configs
gems: [jekyll-paginate, jekyll-tidy]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: MooseV2
repo: desouzali
branch: master
relative_source: ../source/
destination: ../docs
source_url:      https://github.com/biomadeira/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
